### ISSUE TITLE
Preview mode conflicts with FireGestures plugin

### ISSUE THREAD

**Issue by tiatin** [nvgtx/tab-focus#2]
Preview mode is enabled. Tab1 is focused. I use gesture from FireGestures plugin to switch to tab2. Now tab2 is active. Then I hover mouse over tab3. Tab-focus plugin previews tab3, which is fine. Now I move away mouse, and tab1 becomes active, but tab2 should! Looks like tab-focus registers "tab is active" flag only if user clicks the tab, but tab can become active not only by mouse clicking on it. In this example, it can become active by fire gesture.

**Comment by nvgtx** [comment]
That behaviour is as expected.
It is not possible to monitor the active tab pointer for its current state continuesly. If another addon sets another tab to active, this will not be noticed.
Because tab focus works entirely on events (which are not dispatched when another addon changes the reference).

The only option to detect foreign interferences would be to poll all open tabs for their state continuesly - but that would have **severe** performace consequences.

If combined functionality is required, it would be recommended combine the the two addons into one as only then the functionality can be syncronized properly.
