### ISSUE TITLE
Needs compatible version for Firefox Quantum

### ISSUE THREAD

**Issue by bejondshao** [nvgtx/tab-focus#4]
Hi there,
    Firefox has updated policy so that this add on is not available in latest firefox now. Would you like to update it? Thank you very much.

**Comment by nvgtx** [comment]
Sadly that's not possible. Firefox Quantum only supports WebExtensions, which do not allow access to tabs in a way to make this addon work. WebExtensions only allow access to web content and cosmetics, but not to core browser functionality. Afaik this was an intentional decision by Mozilla, so there's not much I can do about it.

**Comment by bejondshao** [comment]
Hi @nvgtx , I install latest firefox nightly (62.0a1 (2018-05-13) (64-bit)) and set `extensions.legacy.enabled` to `true` and set `xpinstall.signatures.required` to `false` in `about:config`. Now I can use tab focus. But a new issue each time I restart firefox nightly, the tab focus doesn't work. I look add-ons configuration, tab focus is enabled. I have to disable it and enable it to make it work. Would you help me to check this? Thank you.

**Comment by nvgtx** [comment]
Hi,
that means during startup Firefox doesn't execute the bootstrap code of the
extension anymore. But it does when you toggle the extension manually. Best
guess, there is a setting in the about:config missing (that, or they simply
removed that functionality without caring for the legacy code).

**Comment by bejondshao** [comment]
Fine, I'll ask on firefox nightly forum.
